=== xuchang86/xyp-manager/WebRoot/WEB-INF/config/system.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  <xs:element name="application">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameter" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" minOccurs="0"/>
        <xs:element ref="key"/>
        <xs:element ref="value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="key">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="value">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== xuchang86/xyp-manager/WebRoot/WEB-INF/config/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="system.xsd">
    <!--系统设置 start-->
    <parameter>
        <description>系统名称</description>
        <key>systemName</key>
        <value>xiaoyao</value>
    </parameter>

    <parameter>
        <description>系统代码</description>
        <key>systemCode</key>
        <value>xiaoyao</value>
    </parameter>

    <parameter>
        <description>验证码登录</description>
        <key>checkRandomCode</key>
        <value>false</value>
    </parameter>

    <!--文件上传设置 start-->
    <parameter>
        <description>图片上传目录</description>
        <key>tempDirectory</key>
        <value>/pictures</value>
    </parameter>

    <parameter>
        <description>文件上传内存占用大小</description>
        <key>maxMemorySize</key>
        <value>10240</value>
    </parameter>

    <parameter>
        <description>文件上传最大尺寸</description>
        <key>maxRequestSize</key>
        <value>1024000</value>
    </parameter>

    <parameter>
        <description>文件上传字符集</description>
        <key>uriEncoding</key>
        <value>UTF-8</value>
    </parameter>
    <!--文件上传设置 end-->

    <!--报表打印设置 start-->
    <parameter>
        <description>报表applet包名称</description>
        <key>reportApplet</key>
        <value>PrintApplet.jar</value>
    </parameter>

    <parameter>
        <description>报表编译参数</description>
        <key>reportComplie</key>
        <value>true</value>
    </parameter>

    <parameter>
        <description>报表文件路径参数</description>
        <key>reportPath</key>
        <value>/WEB-INF/reports</value>
    </parameter>
    <!--报表打印设置 end-->
</application>
